[profile.default]
src = 'contracts'
out = 'out'
fuzz_runs = 5000
libs = ['lib']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]
[rpc_endpoints]
optimism="${OPTIMISIM_RPC_URL}"

[fmt]
line_length = 120
quote_style = 'single'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
